/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mostcommonword;

public class App {
    public static void main(String[] args) {
        String book = "In a galaxy far far away";
        String mostCommon = MostCommonWord.findMostCommonWord(book);
        System.out.println("Most common word: " + mostCommon);
    }
}
