/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package insertionsort;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    public void testInsertionSort() {
        int[] arr = {12, 11, 13, 5, 6};
        int[] sortedArr = {5, 6, 11, 12, 13};

        Insertion.insertionSort(arr);

        assertArrayEquals(sortedArr, arr);
    }
}
