/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashtable;

import java.util.List;

public class App {

    public static void main(String[] args) {

        Hashtable hashtable = new Hashtable(10);

        hashtable.set("name", "John Doe");
        hashtable.set("age", "30");
        hashtable.set("email", "john@example.com");
        String name = hashtable.get("name");
        String age = hashtable.get("age");
        String email = hashtable.get("email");

        System.out.println("Name: " + name);
        System.out.println("Age: " + age);
        System.out.println("Email: " + email);

        System.out.println("Has 'name': " + hashtable.has("name"));
        System.out.println("Has 'city': " + hashtable.has("city"));

        List<String> keys = hashtable.keys();
        System.out.println("Keys: " + keys);

        hashtable.set("age", "31");
        System.out.println("Updated Age: " + hashtable.get("age"));
    }
}
