/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stackqueue;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
   @Test
    public void testStackPush()
   {
       LinckedStack lstest=new LinckedStack();
       lstest.push(2);
       lstest.push(4);
       lstest.push(6);
       assertEquals(3,lstest.length);
   }
   @Test
    public void testStackPop()
   {
       LinckedStack lstest=new LinckedStack();
       lstest.push(2);
       lstest.push(4);
       lstest.push(6);
       int removedItem=lstest.pop();
       assertEquals(6,removedItem);
   }
   @Test
    public void testStackPeek()
   {
       LinckedStack lstest=new LinckedStack();
       lstest.push(2);
       lstest.push(4);
       lstest.push(6);
       int peekElement=lstest.peek();
       assertEquals(6,peekElement);
   }
   @Test
    public void testQueueEnqueue()
   {
       LinkedQueue lntest =new LinkedQueue();
       lntest.enqueue(1);
       lntest.enqueue(3);
       lntest.enqueue(5);
       assertEquals(3,lntest.length);
   }
   @Test
    public void testQueueDequeue()
   {
       LinkedQueue lntest =new LinkedQueue();
       lntest.enqueue(1);
       lntest.enqueue(3);
       lntest.enqueue(5);
       int removedElement=lntest.dequeue();
       assertEquals(1,removedElement);
   }
   @Test
    public void testQueuePeek()
   {
       LinkedQueue lntest =new LinkedQueue();
       lntest.enqueue(1);
       lntest.enqueue(3);
       lntest.enqueue(5);
       int peekElement=lntest.peek();
       assertEquals(1,peekElement);
   }
}
