/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tree;

import org.junit.jupiter.api.Test;

import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    public void testEmptyTree() {
        BinaryTree tree = new BinaryTree();
        assertNull(tree.root);
    }
    @Test
    public void testSingleNodeTree() {
        BinaryTree tree = new BinaryTree();
        tree.root = new BinaryTree.Node(5);
        assertEquals(5, tree.root.value);
        assertNull(tree.root.left);
        assertNull(tree.root.right);
    }

    @Test
    public void testPreOrderTraversal() {
        BinaryTree tree = new BinaryTree();
        tree.root = new BinaryTree.Node(1);
        tree.root.left = new BinaryTree.Node(2);
        tree.root.right = new BinaryTree.Node(3);
        tree.root.left.left = new BinaryTree.Node(4);
        tree.root.left.right = new BinaryTree.Node(5);

        List<Integer> preOrderResult = tree.preOrderTraversal(tree.root);
        assertEquals(List.of(1, 2, 4, 5, 3), preOrderResult);
    }

    @Test
    public void testInOrderTraversal() {
        BinaryTree tree = new BinaryTree();
        tree.root = new BinaryTree.Node(1);
        tree.root.left = new BinaryTree.Node(2);
        tree.root.right = new BinaryTree.Node(3);
        tree.root.left.left = new BinaryTree.Node(4);
        tree.root.left.right = new BinaryTree.Node(5);

        List<Integer> inOrderResult = tree.inOrderTraversal(tree.root);
        assertEquals(List.of(4, 2, 5, 1, 3), inOrderResult);
    }

    @Test
    public void testPostOrderTraversal() {
        BinaryTree tree = new BinaryTree();
        tree.root = new BinaryTree.Node(1);
        tree.root.left = new BinaryTree.Node(2);
        tree.root.right = new BinaryTree.Node(3);
        tree.root.left.left = new BinaryTree.Node(4);
        tree.root.left.right = new BinaryTree.Node(5);

        List<Integer> postOrderResult = tree.postOrderTraversal(tree.root);
        assertEquals(List.of(4, 5, 2, 3, 1), postOrderResult);
    }
}
