/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linklist;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    public void testInsert() {
    Linkylist testlink =new Linkylist();
    testlink.insert(1);
    testlink.insert(0);
    assertEquals("{0} -> {1} -> NULL", testlink.to_string());
    }
    @Test
    public void testInclude()
    {
        Linkylist testlink =new Linkylist();
        testlink.insert(1);
        testlink.insert(0);
        testlink.includes(1);
        assertEquals(true,true);
    }
}
